package org.usfirst.frc308.FRC2018308.subsystems;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;

import org.usfirst.frc308.FRC2018308.Robot;
import org.usfirst.frc308.FRC2018308.RobotMap;
import org.usfirst.frc308.FRC2018308.commands.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;

public class Claw extends Subsystem{

	public static Solenoid clawSolenoid = RobotMap.clawSolenoid; 
	@Override
	protected void initDefaultCommand() {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public void periodic() {
		
	}
	
	public void openClaw() {
		Claw.clawSolenoid.set(true);;
	}
	
	public void closeClaw() {
		Claw.clawSolenoid.set(false);
	}

}
