package org.usfirst.frc308.FRC2017308.subsystems;
import org.usfirst.frc308.FRC2017308.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;

public class Claw extends Subsystem{

	@Override
	protected void initDefaultCommand() {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public void periodic() {
		
	}

}
